name: modmidi
sha1: 64a9eb5c2885e9b41e9f06b27607784126d5fb4f
options:
    # paths
    basename: modmidi.irx
    target_path: in/modmidi.irx
    base_path: ..
    
    asm_path: asm/modmidi
    src_path: src/modmidi
    asset_path: assets/modmidi
    build_path: build
    subalign: 4

    extensions_path: tools/splat_ext 
    symbol_addrs_path: config/modmidi_symbol_addrs.txt
    undefined_funcs_auto_path: config/modmidi_undefined_funcs_auto.txt
    undefined_syms_auto_path:  config/modmidi_undefined_syms_auto.txt

    named_regs_for_c_funcs: True
    
    # compiler 
    compiler: GCC
    platform: psx

    string_encoding: ASCII
    
    section_order: [".iopmod", ".text", ".rel.text", ".rodata", ".rel.rodata", ".data", ".rel.data", ".sbss", ".bss"]

segments:
    - [0, databin, elf_header]
    - [0x74, databin, iopmod]
    - name: text
      type: code
      start: 0xb0
      vram: 0x0
      bss_size: 0x4
      subsegments:
        # .text
        - [0xb0, asm]
        - [0x760, asm]
        - [0x840, asm]
        - [0x2600, asm]
        - [0x3750, asm]
        - [0x37E0, asm]
        - [0x3830, asm]
         # .rodata
        - [0x3890, rodata]
        - [0x3930, rodata]
        - [0x3BD0, rodata]
        # .data
        - [0x3ef0, data]
        # .bss
        - { start: 0x3f80, type: bss, vram: 0x3ed0 }
        
    - [0x3f80, databin] # .shstrtab
    - [0x41bc, databin] # .rel.text
    - [0x4e5c, databin] # .rel.rodata
    - [0x557c, databin] # .rel.data
    - [0x55a4, databin] # .symtab
    - [0x55b4, databin] # .strtab
